#!/usr/bin/env python3
"""Modpack upload backend.

POST /api/upload         — receives .mrpack file, saves to /data/incoming/<name>.mrpack
GET  /upload/            — handled by nginx static (upload.html)
GET  /api/panel/status   — server switch panel: current state (needs X-Panel-Token)
POST /api/panel/action   — server switch panel: use/main/stop (needs X-Panel-Token)

The panel does NOT talk to Docker. It forwards a closed set of operations to
mcswitch-agent over a Unix socket that the host shares through /data.
"""
import os
import re
import sys
import json
import hmac
import shutil
import socket
import hashlib
import logging
import threading
import time
from pathlib import Path
from datetime import datetime
from flask import Flask, request, jsonify, abort

INCOMING = Path("/data/incoming")
FILES = Path("/data/files")
LOGS = Path("/data/logs")
PROCESSED = Path("/data/processed")

for d in (INCOMING, FILES, LOGS, PROCESSED):
    d.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.FileHandler(LOGS / "upload.log"), logging.StreamHandler()],
)
log = logging.getLogger("uploader")

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 200 * 1024 * 1024  # 200 MB

# Mark file as "seen" so the processor cron doesn't double-process
PROCESSED_MARKER = Path("/data/.processed.json")
HTPASSWD = Path("/data/.htpasswd")

# === Server switch panel ===
# Socket published by mcswitch-agent on the host (visible here via the /data mount)
MCSWITCH_SOCKET = Path("/data/.mcswitch.sock")
PANEL_TOKEN_PATH = Path("/data/.panel-token")
PANEL_HTML = Path("/var/www/html/panel.html")
PANEL_UPLOAD_HTML = Path("/var/www/html/panel-upload.html")
# Whatever the browser asks for, only these three ever reach the agent.
PANEL_OPS = {"use", "main", "stop", "set"}
PROFILE_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,31}$")


def check_basic_auth(header_value: str) -> bool:
    """Validate 'Authorization: Basic base64(user:pass)' against .htpasswd."""
    if not header_value or not header_value.startswith("Basic "):
        return False
    import base64
    try:
        decoded = base64.b64decode(header_value[6:]).decode("utf-8", errors="strict")
    except Exception:
        return False
    if ":" not in decoded:
        return False
    user, _, password = decoded.partition(":")
    if not HTPASSWD.exists():
        return False
    # apache htpasswd format: user:{SHA}base64hash  OR  user:$apr1$salt$hash
    # We only support the {SHA} variant generated by `htpasswd -s`.
    import base64 as b64
    import hashlib as hl
    expected_pw_hash = b64.b64encode(hl.sha1(password.encode("utf-8")).digest()).decode("ascii")
    expected = f"{user}:{{SHA}}{expected_pw_hash}"
    for line in HTPASSWD.read_text().splitlines():
        if line.strip() == expected:
            return True
    return False


def load_processed() -> dict:
    if PROCESSED_MARKER.exists():
        try:
            return json.loads(PROCESSED_MARKER.read_text())
        except Exception:
            pass
    return {"files": {}}


def save_processed(d: dict) -> None:
    PROCESSED_MARKER.write_text(json.dumps(d, indent=2))


def safe_filename(name: str) -> str:
    """Strip path components + enforce .mrpack extension."""
    name = os.path.basename(name)
    name = re.sub(r"[^A-Za-z0-9._\-]", "_", name)
    if not name.endswith(".mrpack"):
        # If user uploaded .zip or other, force .mrpack
        name = re.sub(r"\.[A-Za-z0-9]+$", "", name) + ".mrpack"
    return name


def detect_format(path: Path) -> dict:
    """Quick sanity check on the uploaded file."""
    try:
        with open(path, "rb") as f:
            head = f.read(4)
    except Exception as e:
        return {"ok": False, "error": f"unreadable: {e}"}

    # ZIP magic = PK\x03\x04 (mrpack is a zip)
    if head[:2] == b"PK":
        # Try to find manifest.json inside the zip
        import zipfile
        try:
            with zipfile.ZipFile(path) as zf:
                names = zf.namelist()
                has_manifest = "modrinth.index.json" in names
                mc_version = None
                loader = None
                if has_manifest:
                    import json as j
                    m = j.loads(zf.read("modrinth.index.json"))
                    mc_version = m.get("dependencies", {}).get("minecraft")
                    loader_key = m.get("dependencies", {}).get("fabric-loader") \
                                 or m.get("dependencies", {}).get("forge") \
                                 or m.get("dependencies", {}).get("quilt-loader")
                    loader = loader_key
                return {
                    "ok": True,
                    "format": "mrpack (zip)",
                    "size": path.stat().st_size,
                    "files_in_zip": len(names),
                    "has_manifest": has_manifest,
                    "mc_version": mc_version,
                    "loader": loader,
                }
        except zipfile.BadZipFile:
            return {"ok": False, "error": "not a valid zip"}
    elif head[:4] == b"\x50\x4b\x05\x06":
        return {"ok": False, "error": "empty zip archive"}
    else:
        return {"ok": False, "error": f"unknown format, magic={head[:4].hex()}"}


@app.route("/api/upload", methods=["POST"])
def upload():
    # Validate Basic Auth header (XHR from browser cannot re-send it via native prompt)
    auth = request.headers.get("Authorization", "")
    if not check_basic_auth(auth):
        log.warning(f"REJECTED upload from {request.remote_addr}: bad auth")
        return jsonify({"ok": False, "error": "unauthorized"}), 401

    if "file" not in request.files:
        return jsonify({"ok": False, "error": "no file part"}), 400
    f = request.files["file"]
    if not f.filename:
        return jsonify({"ok": False, "error": "empty filename"}), 400

    name = safe_filename(f.filename)
    dest = INCOMING / name
    tmp = dest.with_suffix(dest.suffix + ".part")

    # Save to .part first (needed to compute SHA before any dedupe check)
    f.save(tmp)

    # Compute SHA256 of uploaded content
    sha = hashlib.sha256()
    with open(tmp, "rb") as r:
        for chunk in iter(lambda: r.read(65536), b""):
            sha.update(chunk)
    digest = sha.hexdigest()

    # === Dedupe by SHA256 ===
    seen = load_processed()
    for prev_name, prev in seen.get("files", {}).items():
        if prev.get("sha256") == digest:
            tmp.unlink(missing_ok=True)
            log.info(f"REJECTED DUPLICATE {name} (sha={digest[:12]} matches {prev_name})")
            return jsonify({
                "ok": False,
                "error": "duplicate",
                "existing_file": prev_name,
                "received_at": prev.get("received_at"),
                "message": f"this file was already uploaded as '{prev_name}'",
            }), 409

    # === Dedupe by filename ===
    # If same filename + different content, suffix with -N so we keep history
    if dest.exists():
        stem = dest.stem
        for n in range(2, 100):
            candidate = INCOMING / f"{stem}-{n}.mrpack"
            if not candidate.exists():
                new_name = candidate.name
                new_dest = candidate
                new_tmp = new_dest.with_suffix(new_dest.suffix + ".part")
                # Move the just-uploaded .part to the new path
                shutil.move(str(tmp), str(new_tmp))
                name = new_name
                dest = new_dest
                tmp = new_tmp
                log.info(f"filename collision, renamed to {name}")
                break

    info = detect_format(tmp)
    if not info["ok"]:
        tmp.unlink(missing_ok=True)
        return jsonify({"ok": False, "error": info["error"]}), 400

    tmp.rename(dest)
    stat = dest.stat()

    # === Copy to public files/ (with filename dedupe) ===
    public_dest = FILES / name
    if public_dest.exists():
        existing_sha = hashlib.sha256()
        with open(public_dest, "rb") as r:
            for chunk in iter(lambda: r.read(65536), b""):
                existing_sha.update(chunk)
        if existing_sha.hexdigest() != digest:
            stem = public_dest.stem
            for n in range(2, 100):
                cand = FILES / f"{stem}-{n}.mrpack"
                if not cand.exists():
                    public_dest = cand
                    break
    shutil.copy2(dest, public_dest)

    # Mark as seen (processor will pick up)
    seen["files"][name] = {
        "received_at": datetime.utcnow().isoformat() + "Z",
        "size": stat.st_size,
        "sha256": digest,
        "info": info,
        "status": "pending",
    }
    save_processed(seen)

    log.info(f"RECEIVED {name} ({stat.st_size} bytes, sha={digest[:12]})")

    return jsonify({
        "ok": True,
        "filename": name,
        "size": stat.st_size,
        "sha256": digest,
        "format": info,
        "download_url": f"/files/{name}",
        "message": "received, queued for processing",
    })


@app.route("/api/status")
def status():
    seen = load_processed()
    incoming = sorted(p.name for p in INCOMING.glob("*.mrpack"))
    files = sorted(p.name for p in FILES.glob("*.mrpack"))
    return jsonify({
        "ok": True,
        "incoming": incoming,
        "files_ready": files,
        "processed": seen.get("files", {}),
    })


def panel_token() -> str:
    try:
        return PANEL_TOKEN_PATH.read_text().strip()
    except Exception:
        return ""


def check_panel_auth() -> bool:
    """Constant-time compare of the X-Panel-Token header."""
    expected = panel_token()
    got = request.headers.get("X-Panel-Token", "")
    return bool(expected) and hmac.compare_digest(expected, got)


def _serve_panel_html(path):
    """Serve a panel HTML file with the API token baked in.

    nginx already required Basic Auth to get here; we re-check the same
    credentials so the token is never handed out on the strength of a
    misconfigured location block alone. The person logs in once, with the
    upload credentials, and never sees or types the token.
    """
    if not check_basic_auth(request.headers.get("Authorization", "")):
        return ("unauthorized", 401,
                {"WWW-Authenticate": 'Basic realm="Modpack Upload"'})
    try:
        html = path.read_text(encoding="utf-8")
    except Exception as exc:
        log.error(f"serve panel html {path}: {exc}")
        return "no disponible", 500
    html = html.replace("__PANEL_TOKEN__", panel_token())
    return html, 200, {"Content-Type": "text/html; charset=utf-8",
                       "Cache-Control": "no-store"}


@app.route("/panel/")
@app.route("/panel")
def panel_page():
    return _serve_panel_html(PANEL_HTML)


@app.route("/panel/upload")
@app.route("/panel/upload/")
def panel_upload_page():
    return _serve_panel_html(PANEL_UPLOAD_HTML)


def agent_call(payload: dict, timeout: int = 25) -> dict:
    """Send one JSON request to mcswitch-agent and read one JSON reply."""
    if not MCSWITCH_SOCKET.exists():
        raise RuntimeError("el agente mcswitch no esta disponible")
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.settimeout(timeout)
    try:
        s.connect(str(MCSWITCH_SOCKET))
        s.sendall(json.dumps(payload).encode() + b"\n")
        buf = b""
        while not buf.endswith(b"\n"):
            chunk = s.recv(65536)
            if not chunk:
                break
            buf += chunk
    finally:
        s.close()
    if not buf:
        raise RuntimeError("el agente no respondio")
    return json.loads(buf.decode("utf-8"))


@app.route("/api/panel/status")
def panel_status():
    if not check_panel_auth():
        return jsonify({"ok": False, "error": "unauthorized"}), 401
    try:
        return jsonify(agent_call({"op": "status"}))
    except Exception as exc:
        log.error(f"panel status: {exc}")
        return jsonify({"ok": False, "error": str(exc)}), 503


@app.route("/api/panel/action", methods=["POST"])
def panel_action():
    if not check_panel_auth():
        log.warning(f"REJECTED panel action from {request.remote_addr}: bad token")
        return jsonify({"ok": False, "error": "unauthorized"}), 401

    body = request.get_json(silent=True) or {}
    op = body.get("op")
    if op not in PANEL_OPS:
        return jsonify({"ok": False, "error": "operacion no permitida"}), 400

    payload = {"op": op}
    if op in ("use", "set"):
        profile = str(body.get("profile", ""))
        if not PROFILE_RE.match(profile):
            return jsonify({"ok": False, "error": "nombre de perfil invalido"}), 400
        payload["profile"] = profile

    if op == "set":
        changes = body.get("changes")
        if not isinstance(changes, dict) or not changes:
            return jsonify({"ok": False, "error": "no hay cambios"}), 400
        # El agente revalida clave por clave; aqui solo se acota el tamano.
        payload["changes"] = {str(k): ("" if v is None else str(v))
                              for k, v in list(changes.items())[:60]}

    log.info(f"PANEL action={op} profile={payload.get('profile', '-')} "
             f"from={request.remote_addr}")
    try:
        return jsonify(agent_call(payload))
    except Exception as exc:
        log.error(f"panel action: {exc}")
        return jsonify({"ok": False, "error": str(exc)}), 503


@app.route("/api/panel/upload", methods=["POST"])
def panel_upload():
    """Upload a .mrpack straight onto a lab profile.

    Deliberately NOT the same path as /api/upload: that one drops the file in
    /data/incoming, where the cron picks it up and deploys it to the main
    server. Here the file only lands in /data/files (so it stays downloadable
    and reusable) and the profile's MODPACK is pointed at it. The main server
    is left alone.
    """
    if not check_panel_auth():
        log.warning(f"REJECTED panel upload from {request.remote_addr}: bad token")
        return jsonify({"ok": False, "error": "unauthorized"}), 401

    profile = str(request.form.get("profile", ""))
    if not PROFILE_RE.match(profile) or profile == "main":
        return jsonify({"ok": False, "error": "perfil invalido"}), 400

    if "file" not in request.files:
        return jsonify({"ok": False, "error": "no llego ningun archivo"}), 400
    f = request.files["file"]
    if not f.filename:
        return jsonify({"ok": False, "error": "nombre de archivo vacio"}), 400

    name = safe_filename(f.filename)
    dest = FILES / name
    tmp = dest.with_suffix(dest.suffix + ".part")
    f.save(tmp)

    info = detect_format(tmp)
    if not info["ok"]:
        tmp.unlink(missing_ok=True)
        return jsonify({"ok": False, "error": info["error"]}), 400

    # Mismo nombre y contenido distinto: se conserva el anterior
    if dest.exists():
        old = hashlib.sha256(dest.read_bytes()).hexdigest()
        new = hashlib.sha256(tmp.read_bytes()).hexdigest()
        if old != new:
            stem = dest.stem
            for n in range(2, 100):
                cand = FILES / f"{stem}-{n}.mrpack"
                if not cand.exists():
                    dest = cand
                    name = cand.name
                    break
    tmp.replace(dest)

    url = f"{request.headers.get('X-Forwarded-Proto', 'https')}://" \
          f"{request.headers.get('X-Forwarded-Host', request.host)}/files/{name}"

    log.info(f"PANEL upload {name} ({dest.stat().st_size} bytes) -> perfil {profile}")
    try:
        res = agent_call({"op": "set", "profile": profile,
                          "changes": {"MODPACK": url}})
    except Exception as exc:
        log.error(f"panel upload set: {exc}")
        return jsonify({"ok": False, "error": str(exc)}), 503

    if not res.get("ok"):
        return jsonify(res), 400
    return jsonify({
        "ok": True,
        "filename": name,
        "url": url,
        "size": dest.stat().st_size,
        "mc_version": info.get("mc_version"),
        "needs_restart": res.get("needs_restart", False),
    })


@app.route("/health")
def health():
    return "ok", 200


if __name__ == "__main__":
    # Listen on localhost only (nginx in front)
    app.run(host="127.0.0.1", port=5050, debug=False, threaded=True)
